import Head from 'next/head';
import HomePage from '@/components/home/HomePage';
import Login from '@/components/login/Login';
import { useEffect } from 'react';
import { useRouter } from 'next/router';

import { useAuthContext } from '@/utils/context/AuthContext';

const Home = () => {
  const { loggedInUser } = useAuthContext();
  const router = useRouter();
  useEffect(() => {
    const accessToken = window.localStorage.getItem('accessToken');

    if (!accessToken) {
      !loggedInUser && router.push('/login');
    }
  }, [loggedInUser, router]);

  return (
    <div>
      <Head>
        <title>Todo App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HomePage />
    </div>
  );
};

export default Home;
