import Head from 'next/head';
import HomePage from '@/components/home/HomePage';
import Login from '@/components/login/Login';
import { useEffect } from 'react';
import { useRouter } from 'next/router';

import { useAuthContext } from '@/utils/context/AuthContext';

const Home = () => {
  const { loggedInUser } = useAuthContext();
  // const router = useRouter();
  // useEffect(() => {
  //   console.log('rendered', loggedInUser);
  //   if (!loggedInUser) {
  //     router.push('/login');
  //   }
  // }, [loggedInUser]);

  return (
    <div>
      <Head>
        <title>Todo App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {loggedInUser ? <HomePage /> : <Login />}
      {/* <Login /> */}
      {/* <HomePage /> */}
    </div>
  );
};

export default Home;
